# Generated by Django 5.1.1 on 2025-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('general-medicine', 'General Medicine'), ('cardiology', 'Cardiology'), ('diabetes', 'Diabetes Care'), ('gynecology', 'Gynecology & Obstetrics'), ('maternity', 'Maternity Care'), ('pharmacy', 'Pharmacy')], default='general-medicine', max_length=100),
        ),
    ]
