# Generated by Django 5.1.1 on 2025-11-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0002_alter_appointment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
    ]
