# Generated by Django 5.1.1 on 2025-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0005_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Blood Pressure'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pulse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sugar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
