# Generated by Django 5.1.1 on 2025-12-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0006_appointment_bp_appointment_pulse_appointment_sugar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('date_of_admission', models.DateTimeField()),
                ('date_of_discharge', models.DateTimeField(auto_now_add=True)),
                ('hb', models.CharField(blank=True, max_length=50, verbose_name='Hemoglobin')),
                ('tlc', models.CharField(blank=True, max_length=50, verbose_name='Total Leucocyte Count')),
                ('platelets', models.CharField(blank=True, max_length=50)),
                ('bul', models.CharField(blank=True, max_length=50, verbose_name='Blood Urea Level')),
                ('creatinine', models.CharField(blank=True, max_length=50)),
                ('condition_on_admission', models.TextField(blank=True)),
                ('condition_on_discharge', models.TextField(blank=True)),
                ('treatment_given', models.TextField(help_text='In-hospital treatment details')),
                ('treatment_advised', models.TextField(help_text='Medications for home with directions')),
                ('follow_up', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.patientprofile')),
            ],
        ),
    ]
