# Generated by Django 5.1.1 on 2025-12-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0007_dischargesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comorbidities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='other_comorbidities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='personal_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
