# Generated by Django 5.1.1 on 2025-12-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0011_patientprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_doctor_code',
            field=models.CharField(choices=[('GYN', 'Gynecology'), ('MED', 'General Medicine')], default='MED', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='reg_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='DoctorPatientCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.doctor')),
            ],
        ),
    ]
