# Generated by Django 4.2.17 on 2025-12-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0012_patientprofile_assigned_doctor_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10, unique=True)),
                ('bed_type', models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('Special', 'Special')], max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IPD_Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(max_length=50, unique=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulsehospital.doctor')),
                ('bed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulsehospital.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OT_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=200)),
                ('ot_number', models.CharField(max_length=20)),
                ('surgery_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('lead_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IPD_DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('saline_details', models.TextField(blank=True)),
                ('injection_details', models.TextField(blank=True)),
                ('other_notes', models.TextField(blank=True)),
                ('vitals', models.CharField(max_length=100)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='pulsehospital.ipd_admission')),
            ],
        ),
    ]
