# Generated by Django 4.2.17 on 2025-12-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0013_bed_ipd_admission_visitorcount_ot_management_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=255)),
                ('ot_date', models.DateField()),
                ('ot_time', models.TimeField()),
                ('anaesthesia_type', models.CharField(blank=True, max_length=100)),
                ('assistant_surgeon', models.CharField(blank=True, max_length=255)),
                ('anaesthetist_name', models.CharField(blank=True, max_length=255)),
                ('pre_op_diagnosis', models.TextField(blank=True)),
                ('post_op_diagnosis', models.TextField(blank=True)),
                ('surgical_findings', models.TextField(blank=True)),
                ('procedure_description', models.TextField(blank=True)),
                ('implants_used', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.doctor')),
            ],
        ),
    ]
