# Generated by Django 4.2.17 on 2025-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0015_otbooking_patient_age_otbooking_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='ct_scan',
            field=models.TextField(blank=True, verbose_name='CT Scan Findings'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='final_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='lft',
            field=models.CharField(blank=True, max_length=100, verbose_name='LFT (TB/DB/IB)'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='mri',
            field=models.TextField(blank=True, verbose_name='MRI Findings'),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='presenting_complaints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='xray',
            field=models.TextField(blank=True, verbose_name='X-Ray Findings'),
        ),
    ]
