# Generated by Django 4.2.17 on 2025-12-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0016_dischargesummary_ct_scan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True)),
                ('consultation_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ward_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ot_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicine_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulsehospital.ipd_admission')),
                ('ot_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulsehospital.otbooking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsehospital.patientprofile')),
            ],
        ),
    ]
