# Generated by Django 4.2.17 on 2025-12-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0017_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discharged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_discharged', to='pulsehospital.doctor'),
        ),
    ]
