# Generated by Django 4.2.17 on 2026-01-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0018_bill_discharged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='patient_name_snapshot',
            field=models.CharField(blank=True, help_text='Auto-saved from Patient Profile', max_length=150),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='reg_id_snapshot',
            field=models.CharField(blank=True, help_text='Auto-saved Registration ID', max_length=50),
        ),
    ]
