# Generated by Django 4.2.17 on 2026-01-17 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0019_dischargesummary_patient_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd_dailyrecord',
            name='patient_reg_id',
            field=models.CharField(blank=True, help_text='Auto-saved Registration ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipd_dailyrecord',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Record Time'),
            preserve_default=False,
        ),
    ]
