# Generated by Django 4.2.17 on 2026-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0020_ipd_dailyrecord_patient_reg_id_ipd_dailyrecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='discharge_advice',
            field=models.TextField(blank=True, help_text='General advice/diet/rest', verbose_name='Discharge Advice'),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='patient_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='reg_id_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='treatment_advised',
            field=models.TextField(default='[]', help_text='JSON Data: Home Rx'),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='treatment_given',
            field=models.TextField(default='[]', help_text='JSON Data: In-hospital meds'),
        ),
    ]
