# Generated by Django 4.2.17 on 2026-02-19 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulsehospital', '0021_dischargesummary_discharge_advice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipd_admission',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='pulsehospital.bed'),
        ),
    ]
